export const notiesArray = [
    {id: '1',
    title: 'first',
    desc: 'In the Fog where Lambs become Lions.',
    date:'22/2/2002',
    author: 'Des',
    },
    {id: '2',
    title: 'second',
    desc: 'In the Fog where Lambs become Lions.',
    date:'22/2/2002',
    author: 'Ron',
    },
    {id: '3',
    title: 'third',
    desc: 'In the Fog where Lambs become Lions.',
    date:'22/2/2002',
    author: 'James',
    },
    {id: '4',
    title: 'fourth',
    desc: 'In the Fog where Lambs become Lions.',
    date:'22/2/2002',
    author: 'Ross',
    },
    {id: '5',
    title: 'fifth',
    desc: 'In the Fog where Lambs become Lions.',
    date:'22/2/2002',
    author: 'Jake',
    },
]